"""Data structures, schemas, and type definitions for CountLoop.

Implements the data models for the planning graph, nodes, relations,
critic feedback, and generation records as defined in:
"CountLoop: Training-Free High-Instance Image Generation via Iterative Agent Guidance" (TMLR 2026).
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Literal, Optional, Tuple, Union
from pydantic import BaseModel, Field, field_validator, model_validator


class ObjectNode(BaseModel):
    """An object instance in the Planning Graph G = (V, E, B_bg)."""

    id: str = Field(..., description="Unique instance identifier, e.g. 'orange_01'")
    category: str = Field(..., description="Object category, e.g. 'orange', 'cup'")
    pos: List[float] = Field(
        ...,
        description="Normalized [x, y] coordinates of the bounding box center in [0, 1]^2",
    )
    size: List[float] = Field(
        ...,
        description="Normalized [w, h] dimensions of the bounding box in [0, 1]^2",
    )
    depth: float = Field(
        default=0.5,
        description="Depth prior d in [0, 1], where larger values indicate greater distance from viewer",
    )
    color: str = Field(
        default="natural",
        description="Instance color or visual appearance description",
    )
    attrs: List[str] = Field(
        default_factory=list,
        description="Instance-specific attributes (e.g., 'on top layer', 'slightly shadowed')",
    )

    @field_validator("pos")
    @classmethod
    def validate_pos(cls, v: List[float]) -> List[float]:
        if len(v) != 2:
            raise ValueError(f"pos must be [x, y] 2D list, got {v}")
        return [float(max(0.0, min(1.0, x))) for x in v]

    @field_validator("size")
    @classmethod
    def validate_size(cls, v: List[float]) -> List[float]:
        if len(v) != 2:
            raise ValueError(f"size must be [w, h] 2D list, got {v}")
        return [float(max(0.005, min(1.0, s))) for s in v]

    @field_validator("depth")
    @classmethod
    def validate_depth(cls, v: float) -> float:
        return float(max(0.0, min(1.0, v)))

    @property
    def x(self) -> float:
        return self.pos[0]

    @property
    def y(self) -> float:
        return self.pos[1]

    @property
    def w(self) -> float:
        return self.size[0]

    @property
    def h(self) -> float:
        return self.size[1]

    @property
    def area(self) -> float:
        """Normalized bounding box area w * h."""
        return self.w * self.h

    @property
    def bbox_xyxy(self) -> Tuple[float, float, float, float]:
        """Returns normalized bounding box [x_min, y_min, x_max, y_max] in [0, 1]."""
        x_min = max(0.0, self.x - self.w / 2.0)
        y_min = max(0.0, self.y - self.h / 2.0)
        x_max = min(1.0, self.x + self.w / 2.0)
        y_max = min(1.0, self.y + self.h / 2.0)
        return (x_min, y_min, x_max, y_max)

    def pixel_bbox(self, width: int = 1024, height: int = 1024) -> Tuple[int, int, int, int]:
        """Returns integer pixel bounding box (x1, y1, x2, y2)."""
        x1, y1, x2, y2 = self.bbox_xyxy
        return (
            int(round(x1 * width)),
            int(round(y1 * height)),
            int(round(x2 * width)),
            int(round(y2 * height)),
        )


class SpatialRelation(BaseModel):
    """An edge E in the Planning Graph encoding spatial relationships between instances."""

    from_id: str = Field(..., alias="from", description="Source node id")
    to_id: str = Field(..., alias="to", description="Target node id")
    relation: Literal["above", "below", "left-of", "right-of", "near"] = Field(
        ..., description="Directional or proximity relationship"
    )
    dist: float = Field(default=0.1, description="Normalized L2 distance between instance centers")
    angle: float = Field(default=0.0, description="Angular orientation in degrees")

    model_config = {"populate_by_name": True}


class PlanningGraph(BaseModel):
    """Structured planning graph G = (V, E, B_bg) generated by Design VLM and refined by Psi."""

    objects: List[ObjectNode] = Field(
        default_factory=list,
        description="Set of object-instance nodes V",
    )
    relations: List[SpatialRelation] = Field(
        default_factory=list,
        description="Set of relational edges E",
    )
    context: str = Field(
        default="",
        description="Global scene context and background description B_bg",
    )
    prompts: Dict[str, str] = Field(
        default_factory=lambda: {
            "Pd": "a photo of objects",
            "Pbg": "neutral clean background",
        },
        description="Foreground (Pd) and background (Pbg) text prompts",
    )

    @property
    def foreground_prompt(self) -> str:
        return self.prompts.get("Pd", "")

    @property
    def background_prompt(self) -> str:
        return self.prompts.get("Pbg", "")

    @property
    def num_instances(self) -> int:
        return len(self.objects)

    def get_node(self, node_id: str) -> Optional[ObjectNode]:
        """Finds node by ID."""
        for node in self.objects:
            if node.id == node_id:
                return node
        return None

    def depth_sorted_instances(self, reverse: bool = False) -> List[ObjectNode]:
        """Returns instances sorted from Far to Near (increasing depth order).

        In CountLoop's cumulative composition, instances are composed in order
        Far -> Near (depth d: 1.0 -> 0.0 or 0.0 -> 1.0 depending on convention).
        Here higher depth represents further away; composing Far to Near means
        processing descending depth (largest d first) so nearer objects (smaller d)
        overwrite farther ones.
        """
        # Descending depth = Far -> Near (nearer objects overwrite farther ones)
        return sorted(self.objects, key=lambda node: node.depth, reverse=not reverse)

    def validate_constraints(
        self,
        min_area: float = 0.01,
        max_area: float = 0.04,
        min_l2_dist: float = 0.03,
    ) -> Dict[str, Any]:
        """Validates Design VLM spatial constraints against paper specs:

        - Per-instance bbox area: 1/100 <= w*h <= 1/25 (0.01 <= area <= 0.04)
        - Minimum L2 distance >= 0.03
        - Absence of straight rows/columns of length >= 6
        """
        violations = {
            "under_min_area": [],
            "over_max_area": [],
            "too_close_pairs": [],
            "grid_alignment_detected": False,
        }

        # Check area
        for node in self.objects:
            if node.area < min_area:
                violations["under_min_area"].append(node.id)
            elif node.area > max_area:
                violations["over_max_area"].append(node.id)

        # Check distances
        n = len(self.objects)
        for i in range(n):
            for j in range(i + 1, n):
                n1, n2 = self.objects[i], self.objects[j]
                dx = n1.x - n2.x
                dy = n1.y - n2.y
                dist = (dx * dx + dy * dy) ** 0.5
                if dist < min_l2_dist:
                    violations["too_close_pairs"].append((n1.id, n2.id, round(dist, 4)))

        # Simple grid detector: check if 6+ instances share near-identical x or y
        x_coords = sorted(node.x for node in self.objects)
        y_coords = sorted(node.y for node in self.objects)

        def has_run_of_duplicates(coords: List[float], eps: float = 0.01, run_len: int = 6) -> bool:
            current_run = 1
            for i in range(1, len(coords)):
                if abs(coords[i] - coords[i - 1]) <= eps:
                    current_run += 1
                    if current_run >= run_len:
                        return True
                else:
                    current_run = 1
            return False

        if has_run_of_duplicates(x_coords) or has_run_of_duplicates(y_coords):
            violations["grid_alignment_detected"] = True

        return violations

    def to_json(self, indent: int = 2) -> str:
        """Serializes planning graph to JSON string."""
        return self.model_dump_json(indent=indent, by_alias=True)

    @classmethod
    def from_json(cls, json_str: str) -> PlanningGraph:
        """Constructs PlanningGraph from JSON string with fallback cleanup."""
        # Clean any markdown fences if present
        cleaned = json_str.strip()
        if cleaned.startswith("```json"):
            cleaned = cleaned[7:]
        elif cleaned.startswith("```"):
            cleaned = cleaned[3:]
        if cleaned.endswith("```"):
            cleaned = cleaned[:-3]
        data = json.loads(cleaned.strip())
        return cls.model_validate(data)


# ==============================================================================
# Critic VLM & Refinement Schemas
# ==============================================================================

EditType = Literal["move", "add", "remove", "resize", "degrid"]


class EditOperation(BaseModel):
    """A typed edit instruction produced by Critic VLM."""

    type: EditType = Field(
        ...,
        description="Closed edit vocabulary: move | add | remove | resize | degrid",
    )
    targets: List[str] = Field(
        default_factory=list,
        description="Target instance IDs to edit",
    )
    hint: str = Field(
        ...,
        description="Concise spatial instruction for refinement operator Psi",
    )


class CriticScores(BaseModel):
    """Quantitative evaluation scores computed in Critic stage."""

    s_c: float = Field(
        ...,
        description="Normalized count score: max(0, 1 - |c_hat - c_gt| / c_gt)",
    )
    detected_count: int = Field(..., alias="c_hat", description="Detected instance count c_hat")
    target_count: int = Field(..., alias="N", description="Target count N (c_gt)")
    s_a: float = Field(..., description="Aesthetic score in [0, 1] from aesthetic estimator")
    C_acc: float = Field(default=0.0, description="Count accuracy measure")
    S: float = Field(
        ...,
        description="Composite score: S = alpha * s_c + (1 - alpha) * s_a",
    )
    alpha: float = Field(default=0.6, description="Count weight alpha (fixed to 0.6)")

    model_config = {"populate_by_name": True}


class CriticFeedback(BaseModel):
    """Structured critique produced by Critic VLM."""

    scores: CriticScores
    decision: Dict[str, Any] = Field(
        default_factory=lambda: {"continue": True, "reason": "refining"},
        description="Advisory decision dictionary ('continue', 'reason')",
    )
    feedback: Dict[str, Any] = Field(
        ...,
        description="Feedback containing summary, count evaluation, and typed edits list",
    )

    @property
    def edits(self) -> List[EditOperation]:
        """Extracts list of EditOperation models from feedback."""
        raw_edits = self.feedback.get("edits", [])
        parsed = []
        for item in raw_edits:
            if isinstance(item, EditOperation):
                parsed.append(item)
            elif isinstance(item, dict):
                parsed.append(EditOperation.model_validate(item))
        return parsed


class IterationRecord(BaseModel):
    """Snapshot of a single refinement iteration."""

    round_idx: int
    scores: CriticScores
    planning_graph: PlanningGraph
    critic_feedback: CriticFeedback
    reasoning_trace: Optional[str] = None
    image_path: Optional[str] = None
    elapsed_time_sec: float = 0.0


class GenerationResult(BaseModel):
    """Final output bundle from CountLoopPipeline."""

    prompt: str
    target_count: int
    final_count: int
    composite_score: float
    converged: bool
    iterations_run: int
    final_image_path: str
    planning_graph: PlanningGraph
    history: List[IterationRecord]
    total_elapsed_sec: float
